R"===(

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

uniform u32 start;
uniform u32 alloc_size;
uniform layout(binding = 0, r32ui) uimageBuffer octree_nodes;

void main()
{
    u32 tid = (gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x) * 64 + gl_LocalInvocationIndex;
    u32 idx = start + tid;
    if (idx < alloc_size)
    {
        imageStore(octree_nodes, s32(idx), uv4(0, 0, 0, 0));
    }
}

)===";
