#define GlobalConstants_Xbot_Accel_Constant 222.200592f
#define GlobalConstants_Xbot_Animation_Speed 1.000000f
#define GlobalConstants_Render_Use_Debug_Camera 1
#define GlobalConstants_Render_DrawStar 1
#define GlobalConstants_Render_DrawGrass 0
